version: '3.1'

services:
  db:
    image: postgres:13.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example # Use postgres/example credentials
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  pgadmin:
    image: dpage/pgadmin4:5.4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    depends_on:
      - db